const express = require('express');
const bodyParser = require('body-parser');
const app = express();
const mongoose = require('mongoose');
const Project = require('./project');
const routesProject = require('./routesProject');
const controllerProject = require('./controllerProject');
const Employee = require('./employee');
const routesEmployee = require('./routesEmployee');
const controllerEmployee = require('./controllerEmployee');
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
const port = process.env.PORT || 8081;
const router = express.Router();
app.listen(port);
console.log('REST API is runnning at ' + port);
mongoose.connect('mongodb://localhost:27017/company');
app.use('/employees', routesEmployee());
app.use('/projects', routesProject());
